version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vocabulary-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - vocabulary-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: vocabulary-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vocabulary-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: vocabulary-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vocabulary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - vocabulary-network

networks:
  vocabulary-network:
    driver: bridge

volumes:
  dbdata:

