name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, json, pdo, pdo_pgsql
          coverage: none
      
      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --prefer-dist --no-dev --optimize-autoloader --no-interaction
      
      - name: Generate Laravel key (if needed)
        working-directory: ./backend
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
            php artisan key:generate
          fi
      
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      
      - name: Pull Vercel Environment Information
        working-directory: ./backend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build Project Artifacts
        working-directory: ./backend
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy to Vercel
        working-directory: ./backend
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

